### ISSUE TITLE
Attestation Support

### ISSUE THREAD

**Issue by csegarragonz** [csegarragonz/coco-serverless#13]
Breakdown of PRs:
* [x] Calculate launch digest #15 
* [x] Attest launch digest #16 
* [x] Sign container images #19
* [ ] Encrypt container images #20
